#!/bin/sh

if [ "$1" = "/bin/sh" ]; then
  shift
fi

if [ -n "$HTTPS_PORT" ]; then
  FWD="`echo $HTTPS_PORT | sed 's|^tcp://||'`"
elif [ -n "$HTTP_PORT" ]; then
  FWD="`echo $HTTP_PORT | sed 's|^tcp://||'`"
elif [ -n "$APP_PORT" ]; then
  FWD="`echo $APP_PORT | sed 's|^tcp://||'`"
fi

ARGS=""

if [ -n "$NGROK_AUTH" ]; then
  ARGS="-authtoken=$NGROK_AUTH "
fi

# Set the subdomain or hostname, depending on which is set
if [ -n "$NGROK_HOSTNAME" ] && [ -n "$NGROK_AUTH" ]; then
  ARGS="$ARGS -hostname $NGROK_HOSTNAME "
elif [ -n "$NGROK_SUBDOMAIN" ] && [ -n "$NGROK_AUTH" ]; then
  ARGS="$ARGS -subdomain $NGROK_SUBDOMAIN "
elif [ -z "$NGROK_AUTH" ]; then
  echo "You must specify an authentication token after registering at https://ngrok.com to use custom domains."
  exit 1
fi

if [ "$NGROK_PROTOCOL" == "TCP" ]; then
  ARGS="$ARGS -proto=tcp "
fi

if [ -n "$NGROK_USERNAME" ] && [ -n "$NGROK_PASSWORD" ] && [ -n "$NGROK_AUTH" ]; then
  ARGS="$ARGS -httpauth=\"$NGROK_USERNAME:$NGROK_PASSWORD\" "
elif [ -n "$NGROK_USERNAME" ] || [ -n "$NGROK_PASSWORD" ]; then
  if [ -z "$NGROK_AUTH" ]; then
  	echo "You must specify a username, password, and Ngrok authentication token to use the custom HTTP authentication."
    echo "Sign up for an authentication token at https://ngrok.com"
    exit 1
  fi
fi

case "$1" in
  -h|help)  ARGS=$1 ;;
  *)        ARGS="$ARGS -config /.ngrok -log stdout $* $FWD" ;;
esac

exec /bin/ngrok $ARGS
